stages:
  - build
  - publish

image:
  name: node:14.18.1-alpine3.14
before_script:
  - yarn

build:
  stage: build
  tags: [docker]
  script: yarn ci
  artifacts:
    paths:
      - lib/

publish-npm:
  stage: publish
  only:
    - tags
  tags: [docker]
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_PUBLISH_TOKEN}"
    - npm publish --access public
