stages:
  - build
  - publish

image:
  name: node:14.18.1-alpine3.14
before_script:
  - apk add jq git
  # apply version from tag name
  - jq '.version=(if env.CI_COMMIT_TAG == null then "0.0.0-snapshot" else env.CI_COMMIT_TAG end)' package.json > package.json.mod && mv package.json.mod package.json
  - yarn

build:
  stage: build
  tags: [docker]
  script: yarn ci
  artifacts:
    paths:
      - lib/

publish-npm:
  stage: publish
  only:
    - tags
  tags: [docker]
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_PUBLISH_TOKEN}"
    - npm publish --access public
