language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn
script:
  - yarn ci
deploy:
  provider: npm
  skip_cleanup: true
  email: team@netsys.technology
  api_key:
    secure: $SECURE_NPM_KEY
  on:
    tags: true
    repo: mysteriumnetwork/mysterium-vpn-js
